/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApieRouteImport } from './routes/apie'
import { Route as GalerijaRouteImport } from './routes/galerija'
import { Route as KontaktaiRouteImport } from './routes/kontaktai'
import { Route as PaslaugosRouteImport } from './routes/paslaugos'
import { Route as PaslaugosIndexRouteImport } from './routes/paslaugos.index'
import { Route as PaslaugosBalduGamybaRouteImport } from './routes/paslaugos.baldu-gamyba'
import { Route as PaslaugosCncFrezavimasRouteImport } from './routes/paslaugos.cnc-frezavimas'
import { Route as PaslaugosDizaineresPaslaugosRouteImport } from './routes/paslaugos.dizaineres-paslaugos'
import { Route as PaslaugosMdfDazymasRouteImport } from './routes/paslaugos.mdf-dazymas'
import { Route as PaslaugosProjektavimasRouteImport } from './routes/paslaugos.projektavimas'
import { Route as PaslaugosTransportavimasIrMontavimasRouteImport } from './routes/paslaugos.transportavimas-ir-montavimas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApieRoute = ApieRouteImport.update({
  id: '/apie',
  path: '/apie',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerijaRoute = GalerijaRouteImport.update({
  id: '/galerija',
  path: '/galerija',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktaiRoute = KontaktaiRouteImport.update({
  id: '/kontaktai',
  path: '/kontaktai',
  getParentRoute: () => rootRouteImport,
} as any)
const PaslaugosRoute = PaslaugosRouteImport.update({
  id: '/paslaugos',
  path: '/paslaugos',
  getParentRoute: () => rootRouteImport,
} as any)
const PaslaugosIndexRoute = PaslaugosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PaslaugosRoute,
} as any)
const PaslaugosBalduGamybaRoute = PaslaugosBalduGamybaRouteImport.update({
  id: '/baldu-gamyba',
  path: '/baldu-gamyba',
  getParentRoute: () => PaslaugosRoute,
} as any)
const PaslaugosCncFrezavimasRoute = PaslaugosCncFrezavimasRouteImport.update({
  id: '/cnc-frezavimas',
  path: '/cnc-frezavimas',
  getParentRoute: () => PaslaugosRoute,
} as any)
const PaslaugosDizaineresPaslaugosRoute =
  PaslaugosDizaineresPaslaugosRouteImport.update({
    id: '/dizaineres-paslaugos',
    path: '/dizaineres-paslaugos',
    getParentRoute: () => PaslaugosRoute,
  } as any)
const PaslaugosMdfDazymasRoute = PaslaugosMdfDazymasRouteImport.update({
  id: '/mdf-dazymas',
  path: '/mdf-dazymas',
  getParentRoute: () => PaslaugosRoute,
} as any)
const PaslaugosProjektavimasRoute = PaslaugosProjektavimasRouteImport.update({
  id: '/projektavimas',
  path: '/projektavimas',
  getParentRoute: () => PaslaugosRoute,
} as any)
const PaslaugosTransportavimasIrMontavimasRoute =
  PaslaugosTransportavimasIrMontavimasRouteImport.update({
    id: '/transportavimas-ir-montavimas',
    path: '/transportavimas-ir-montavimas',
    getParentRoute: () => PaslaugosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apie': typeof ApieRoute
  '/galerija': typeof GalerijaRoute
  '/kontaktai': typeof KontaktaiRoute
  '/paslaugos': typeof PaslaugosRouteWithChildren
  '/paslaugos/baldu-gamyba': typeof PaslaugosBalduGamybaRoute
  '/paslaugos/cnc-frezavimas': typeof PaslaugosCncFrezavimasRoute
  '/paslaugos/dizaineres-paslaugos': typeof PaslaugosDizaineresPaslaugosRoute
  '/paslaugos/mdf-dazymas': typeof PaslaugosMdfDazymasRoute
  '/paslaugos/projektavimas': typeof PaslaugosProjektavimasRoute
  '/paslaugos/transportavimas-ir-montavimas': typeof PaslaugosTransportavimasIrMontavimasRoute
  '/paslaugos/': typeof PaslaugosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apie': typeof ApieRoute
  '/galerija': typeof GalerijaRoute
  '/kontaktai': typeof KontaktaiRoute
  '/paslaugos/baldu-gamyba': typeof PaslaugosBalduGamybaRoute
  '/paslaugos/cnc-frezavimas': typeof PaslaugosCncFrezavimasRoute
  '/paslaugos/dizaineres-paslaugos': typeof PaslaugosDizaineresPaslaugosRoute
  '/paslaugos/mdf-dazymas': typeof PaslaugosMdfDazymasRoute
  '/paslaugos/projektavimas': typeof PaslaugosProjektavimasRoute
  '/paslaugos/transportavimas-ir-montavimas': typeof PaslaugosTransportavimasIrMontavimasRoute
  '/paslaugos': typeof PaslaugosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apie': typeof ApieRoute
  '/galerija': typeof GalerijaRoute
  '/kontaktai': typeof KontaktaiRoute
  '/paslaugos': typeof PaslaugosRouteWithChildren
  '/paslaugos/baldu-gamyba': typeof PaslaugosBalduGamybaRoute
  '/paslaugos/cnc-frezavimas': typeof PaslaugosCncFrezavimasRoute
  '/paslaugos/dizaineres-paslaugos': typeof PaslaugosDizaineresPaslaugosRoute
  '/paslaugos/mdf-dazymas': typeof PaslaugosMdfDazymasRoute
  '/paslaugos/projektavimas': typeof PaslaugosProjektavimasRoute
  '/paslaugos/transportavimas-ir-montavimas': typeof PaslaugosTransportavimasIrMontavimasRoute
  '/paslaugos/': typeof PaslaugosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apie'
    | '/galerija'
    | '/kontaktai'
    | '/paslaugos'
    | '/paslaugos/baldu-gamyba'
    | '/paslaugos/cnc-frezavimas'
    | '/paslaugos/dizaineres-paslaugos'
    | '/paslaugos/mdf-dazymas'
    | '/paslaugos/projektavimas'
    | '/paslaugos/transportavimas-ir-montavimas'
    | '/paslaugos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apie'
    | '/galerija'
    | '/kontaktai'
    | '/paslaugos/baldu-gamyba'
    | '/paslaugos/cnc-frezavimas'
    | '/paslaugos/dizaineres-paslaugos'
    | '/paslaugos/mdf-dazymas'
    | '/paslaugos/projektavimas'
    | '/paslaugos/transportavimas-ir-montavimas'
    | '/paslaugos'
  id:
    | '__root__'
    | '/'
    | '/apie'
    | '/galerija'
    | '/kontaktai'
    | '/paslaugos'
    | '/paslaugos/baldu-gamyba'
    | '/paslaugos/cnc-frezavimas'
    | '/paslaugos/dizaineres-paslaugos'
    | '/paslaugos/mdf-dazymas'
    | '/paslaugos/projektavimas'
    | '/paslaugos/transportavimas-ir-montavimas'
    | '/paslaugos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApieRoute: typeof ApieRoute
  GalerijaRoute: typeof GalerijaRoute
  KontaktaiRoute: typeof KontaktaiRoute
  PaslaugosRoute: typeof PaslaugosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apie': {
      id: '/apie'
      path: '/apie'
      fullPath: '/apie'
      preLoaderRoute: typeof ApieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerija': {
      id: '/galerija'
      path: '/galerija'
      fullPath: '/galerija'
      preLoaderRoute: typeof GalerijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontaktai': {
      id: '/kontaktai'
      path: '/kontaktai'
      fullPath: '/kontaktai'
      preLoaderRoute: typeof KontaktaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paslaugos': {
      id: '/paslaugos'
      path: '/paslaugos'
      fullPath: '/paslaugos'
      preLoaderRoute: typeof PaslaugosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paslaugos/': {
      id: '/paslaugos/'
      path: '/'
      fullPath: '/paslaugos/'
      preLoaderRoute: typeof PaslaugosIndexRouteImport
      parentRoute: typeof PaslaugosRoute
    }
    '/paslaugos/baldu-gamyba': {
      id: '/paslaugos/baldu-gamyba'
      path: '/baldu-gamyba'
      fullPath: '/paslaugos/baldu-gamyba'
      preLoaderRoute: typeof PaslaugosBalduGamybaRouteImport
      parentRoute: typeof PaslaugosRoute
    }
    '/paslaugos/cnc-frezavimas': {
      id: '/paslaugos/cnc-frezavimas'
      path: '/cnc-frezavimas'
      fullPath: '/paslaugos/cnc-frezavimas'
      preLoaderRoute: typeof PaslaugosCncFrezavimasRouteImport
      parentRoute: typeof PaslaugosRoute
    }
    '/paslaugos/dizaineres-paslaugos': {
      id: '/paslaugos/dizaineres-paslaugos'
      path: '/dizaineres-paslaugos'
      fullPath: '/paslaugos/dizaineres-paslaugos'
      preLoaderRoute: typeof PaslaugosDizaineresPaslaugosRouteImport
      parentRoute: typeof PaslaugosRoute
    }
    '/paslaugos/mdf-dazymas': {
      id: '/paslaugos/mdf-dazymas'
      path: '/mdf-dazymas'
      fullPath: '/paslaugos/mdf-dazymas'
      preLoaderRoute: typeof PaslaugosMdfDazymasRouteImport
      parentRoute: typeof PaslaugosRoute
    }
    '/paslaugos/projektavimas': {
      id: '/paslaugos/projektavimas'
      path: '/projektavimas'
      fullPath: '/paslaugos/projektavimas'
      preLoaderRoute: typeof PaslaugosProjektavimasRouteImport
      parentRoute: typeof PaslaugosRoute
    }
    '/paslaugos/transportavimas-ir-montavimas': {
      id: '/paslaugos/transportavimas-ir-montavimas'
      path: '/transportavimas-ir-montavimas'
      fullPath: '/paslaugos/transportavimas-ir-montavimas'
      preLoaderRoute: typeof PaslaugosTransportavimasIrMontavimasRouteImport
      parentRoute: typeof PaslaugosRoute
    }
  }
}

interface PaslaugosRouteChildren {
  PaslaugosBalduGamybaRoute: typeof PaslaugosBalduGamybaRoute
  PaslaugosCncFrezavimasRoute: typeof PaslaugosCncFrezavimasRoute
  PaslaugosDizaineresPaslaugosRoute: typeof PaslaugosDizaineresPaslaugosRoute
  PaslaugosMdfDazymasRoute: typeof PaslaugosMdfDazymasRoute
  PaslaugosProjektavimasRoute: typeof PaslaugosProjektavimasRoute
  PaslaugosTransportavimasIrMontavimasRoute: typeof PaslaugosTransportavimasIrMontavimasRoute
  PaslaugosIndexRoute: typeof PaslaugosIndexRoute
}

const PaslaugosRouteChildren: PaslaugosRouteChildren = {
  PaslaugosBalduGamybaRoute: PaslaugosBalduGamybaRoute,
  PaslaugosCncFrezavimasRoute: PaslaugosCncFrezavimasRoute,
  PaslaugosDizaineresPaslaugosRoute: PaslaugosDizaineresPaslaugosRoute,
  PaslaugosMdfDazymasRoute: PaslaugosMdfDazymasRoute,
  PaslaugosProjektavimasRoute: PaslaugosProjektavimasRoute,
  PaslaugosTransportavimasIrMontavimasRoute:
    PaslaugosTransportavimasIrMontavimasRoute,
  PaslaugosIndexRoute: PaslaugosIndexRoute,
}

const PaslaugosRouteWithChildren = PaslaugosRoute._addFileChildren(
  PaslaugosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApieRoute: ApieRoute,
  GalerijaRoute: GalerijaRoute,
  KontaktaiRoute: KontaktaiRoute,
  PaslaugosRoute: PaslaugosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
